aws_region: ap-southeast-2
aws_account_id: "043352572184" # prod
org_name: upworth 
notifications_dnx:
  enabled: true
  email: "" # optional
  slack_endpoint: "https://hooks.slack.com/services/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" # optional